/** Real SQLite + Worker handler contract tests. No Cloudflare account/deployment used. */
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import {handle} from '../responses-service/worker.mjs';
import assert from 'node:assert/strict';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('../responses-service/schema.sql',import.meta.url),'utf8'));
const env={ADMIN_TOKEN:'a'.repeat(64),DB:{prepare(sql){const st=db.prepare(sql);let values=[];const wrapper={bind(...v){values=v;return wrapper;},async run(){return st.run(...values)},async first(){return st.get(...values)||null;},async all(){return {results:st.all(...values)}}};return wrapper;}}};
let checks=0;const ok=(x,label)=>{assert.ok(x,label);checks++;console.log('PASS',label)};
const origin='https://example.github.io', root='https://test.account.workers.dev';let tick=Date.now();Date.now=()=>tick;
async function call(path,method='GET',body,admin=false,override={}){const headers={Origin:origin,'CF-Connecting-IP':'192.0.2.12',...override};if(body!==undefined)headers['Content-Type']='application/json';if(admin)headers.Authorization='Bearer '+env.ADMIN_TOKEN;const r=await handle(new Request(root+path,{method,headers,body:body===undefined?undefined:JSON.stringify(body)}),env);let b;try{b=await r.json()}catch{b={}}return {r,b};}
let a=await call('/api/community/submit','POST',{});ok(a.r.status===403,'Disabled-by-default visitor service');
a=await call('/admin/messages');ok(a.r.status===401,'No anonymous access to private inbox');
a=await call('/admin/config','PUT',{origin,enabled:true,researchers:[{id:'one','name':'Test Researcher'}]},true);ok(a.r.status===200,'Owner configures exact HTTPS origin and public names');
a=await call('/api/community/health');ok(a.b.enabled===true&&a.r.headers.get('Access-Control-Allow-Origin')===origin,'Health and explicit CORS');
a=await call('/api/community/health','OPTIONS');ok(a.r.status===204,'Configured preflight succeeds');
a=await call('/api/community/health','OPTIONS',undefined,false,{Origin:'https://evil.example'});ok(a.r.status===403&&!a.r.headers.has('Access-Control-Allow-Origin'),'Cross-origin preflight fails closed');
a=await call('/api/community/challenge','GET',undefined,false,{Origin:'https://evil.example'});ok(a.r.status===403,'Cross-origin challenge denied');
a=await call('/api/community/challenge');const token=a.b.token;ok(token?.length>80,'Signed challenge returned');
const payload={token,subject:'A microscopy question',message:"What does the laboratory's review process involve?",nickname:'Visitor',researcher_id:'one',consent_public:false};
a=await call('/api/community/submit','POST',payload);ok(a.r.status===403,'Minimum form delay enforced');tick+=3000;
a=await call('/api/community/submit','POST',payload);ok(a.r.status===201&&a.b.receipt.length===48,'Anonymous submission succeeds with one-time reply key');const saved=a.b;
a=await call('/api/community/submit','POST',payload);ok(a.r.status===409,'Challenge cannot be replayed');
const raw=db.prepare('SELECT * FROM messages WHERE id=?').get(saved.id);ok(raw.receipt_hash!==saved.receipt&&!Object.keys(raw).some(k=>['ip','email','user_id'].includes(k)),'Only hashed reply key; no IP/email/account stored in message');
a=await call('/api/community/public');ok(a.b.items.length===0,'Pending and private messages are not public');
a=await call('/api/community/lookup','POST',{id:saved.id,receipt:'0'.repeat(48)});ok(a.r.status===404,'Wrong reply key is rejected');
a=await call('/api/community/lookup','POST',{id:saved.id,receipt:saved.receipt});ok(a.r.status===200&&!('receipt_hash'in a.b.item),'Visitor can read only keyed response; hash excluded');
a=await call('/admin/messages');ok(a.r.status===401,'Admin API requires bearer key not Origin alone');
a=await call('/admin/messages','GET',undefined,true);ok(a.b.items.length===1&&!('receipt_hash'in a.b.items[0]),'Authenticated inbox list excludes key hashes');
a=await call('/admin/messages/'+saved.id,'PUT',{reply:'Our team will follow up here.',status:'public'},true);ok(a.r.status===422,'Admin cannot override missing visitor consent');
a=await call('/admin/messages/'+saved.id,'PUT',{reply:'A private laboratory response.',status:'answered'},true);ok(a.r.status===200,'Private reply is saved');
a=await call('/api/community/lookup','POST',{id:saved.id,receipt:saved.receipt});ok(a.b.item.reply==='A private laboratory response.'&&a.b.item.status==='answered','Reply key retrieves actual saved reply');
a=await call('/api/community/challenge');tick+=3000;const publicPayload={...payload,token:a.b.token,consent_public:true,subject:'Public question'};a=await call('/api/community/submit','POST',publicPayload);const pub=a.b;ok(a.r.status===201,'Explicitly consented visitor question accepted');
a=await call('/admin/messages/'+pub.id,'PUT',{reply:'Source-reviewed public reply.',status:'public'},true);ok(a.r.status===200,'Consented response may be deliberately published');
a=await call('/api/community/public');ok(a.b.items.length===1&&a.b.items[0].reply==='Source-reviewed public reply.'&&!('receipt_hash'in a.b.items[0]),'Only consented approved discussion appears publicly');
a=await call('/admin/messages/'+pub.id,'DELETE',{confirm:'NO'},true);ok(a.r.status===422,'Deletion requires explicit confirmation');
a=await call('/admin/messages/'+pub.id,'DELETE',{confirm:'DELETE'},true);ok(a.r.status===200,'Confirmed deletion removes message');
a=await call('/api/community/public');ok(a.b.items.length===0,'Deleted message leaves public feed');
a=await call('/api/community/submit','POST',{message:'a'.repeat(17000)});ok(a.r.status===413,'Streaming body size is bounded');
a=await call('/admin/config','PUT',{origin:'http://insecure.example',enabled:true,researchers:[]},true);ok(a.r.status===422,'Invalid HTTP configuration rejected');
for(let i=0;i<35;i++)a=await call('/api/community/lookup','POST',{id:saved.id,receipt:saved.receipt});ok(a.r.status===429,'Lookup brute-force rate limited');
a=await call('/admin/config','PUT',{origin,enabled:false,researchers:[]},true);ok(a.r.status===200,'Owner can close responses');
a=await call('/api/community/public');ok(a.r.status===403&&a.r.headers.get('Cache-Control')==='no-store','Closure blocks feed and every response is no-store');
a=await handle(new Request(root+'/api/community/health'),{...env,ADMIN_TOKEN:''});ok(a.status===503,'Missing secret is a clear unavailable service not success');
console.log(`${checks} Worker/SQLite contract checks passed; cloud runtime and deployment are not exercised.`);
db.close();
