<?php
declare(strict_types=1);
require __DIR__.'/../php/bootstrap.php';
use Ted2\{Store,Auth,Schema,Records,PublicSite,Publisher,Problem,Literature,Process};
use function Ted2\{json,decode,utc,id,dirPrivate};
$checks=0;
set_error_handler(function($severity,$message,$file,$line){if(error_reporting()&$severity)throw new ErrorException($message,0,$severity,$file,$line);return false;});
function check(bool $ok,string $name):void{global $checks;$checks++;if(!$ok)throw new RuntimeException('FAILED: '.$name);echo "PASS $name\n";}
function rejects(callable $fn,int $status,string $label):void{try{$fn();throw new RuntimeException('Expected rejection: '.$label);}catch(Problem $e){check($e->status===$status,$label);}}
$tmp=sys_get_temp_dir().'/ted2-core-'.id();dirPrivate($tmp);putenv('TED2_DB='.$tmp.'/ted2.sqlite3');
try{
 $s=new Store();$s->init();$v5=decode(file_get_contents(__DIR__.'/../data/v5-baseline.json'));
 foreach($v5 as $c=>$rows)foreach($rows as $p)$s->insert($c,$p,'v5-fixture');
 $p=$s->get('people','paulus-hamutenya');$p['bio']='Owner edited biography must survive.';$p['private_phone']='PRIVATE_MIGRATION_SENTINEL';$s->replace('people',$p,$p['_version'],'fixture');
 $hash=Auth::hash('FixtureOnly!Pass-3821');$s->db->query('INSERT INTO users VALUES(?,?,?,?,?,?,?)',['original-user','old-owner',$hash,'owner','',1,utc()]);$s->db->query('INSERT INTO users VALUES(?,?,?,?,?,?,?)',['old-researcher','old-researcher',$hash,'researcher','paulus-hamutenya',1,utc()]);
 $s->db->query('INSERT INTO sessions VALUES(?,?,?,?,?,?)',['old-session','original-user','csrf',time(),time(),time()+1000]);
 $report=$s->migrate();check(is_file($report['backup']),'private pre-migration database backup');check($s->get('people','paulus-hamutenya')['bio']==='Owner edited biography must survive.','owner biography preserved');check($s->get('people','paulus-hamutenya')['private_phone']==='PRIVATE_MIGRATION_SENTINEL','private field preserved');check($s->db->one('SELECT password_hash FROM users WHERE id=?',['original-user'])['password_hash']===$hash,'legacy password hash unchanged');check(password_verify('FixtureOnly!Pass-3821',$hash),'PHP verifies migrated Argon2 password');check(count($s->db->all('SELECT * FROM sessions'))===0,'legacy sessions revoked, not reused');check((int)$s->db->one('SELECT edit_profile FROM v6_rights WHERE user_id=?',['old-researcher'])['edit_profile']===0,'new researcher profile privilege requires owner grant');
 check(count($s->list('people'))===12,'twelve profiles retained');check(count($s->list('capabilities'))===12,'twelve research descriptions retained');check(count($s->list('publications'))===8,'eight original publication records retained');$before=$s->get('people','paulus-hamutenya')['_version'];$s->migrate();check($s->get('people','paulus-hamutenya')['_version']===$before,'repeat migration is idempotent');
 $s->db->query('CREATE TABLE temp_test(value TEXT)');$sql="Robert'); DROP TABLE users;--";$s->db->query('INSERT INTO temp_test VALUES(?)',[$sql]);check($s->db->one('SELECT value FROM temp_test')['value']===$sql,'prepared binding treats SQL-like input as data');check($s->db->one('SELECT COUNT(*) n FROM users')['n']===2,'users survive injection-shaped input');
 try{$s->db->tx(function()use($s){$s->db->query('INSERT INTO temp_test VALUES(?)',['rolled back']);throw new RuntimeException('deliberate');});}catch(RuntimeException){}check(count($s->db->all('SELECT * FROM temp_test'))===1,'transaction rollback across prepared operations');
 $a=Literature::rank([['id'=>'a','title'=>'Nanomedicine biomarkers'],['id'=>'b','title'=>'Microbial ecology']],['nano','ecology']);$b=Literature::rank([['id'=>'a','title'=>'Nanomedicine biomarkers'],['id'=>'b','title'=>'Microbial ecology']],['nano','ecology'],true);check($a===$b,'C++ and PHP metadata rankers agree');
 $site=new PublicSite($s,true);$one=$site->build($tmp.'/export-one');$two=(new PublicSite($s,true))->build($tmp.'/export-two');check($one['digest']===$two['digest'],'same approved content compiles deterministically');check(!str_contains(file_get_contents($tmp.'/export-one/researchers/paulus-hamutenya/index.html'),'PRIVATE_MIGRATION_SENTINEL'),'private profile field not exported');check(is_file($tmp.'/export-one/researchers/jaydine-feris/index.html'),'correct researcher route exported');
 $names=array_column($site->data['people'],'id');check($names[0]==='albertina-shatri','prioritised PI precedes alphabetic directory');$ordered=array_column(array_slice($site->data['people'],1),'sort_name');$expected=$ordered;usort($expected,'strnatcasecmp');check($ordered===$expected,'unpinned researchers sort alphabetically');
 // A real isolated Git remote tests push without any network or user repository access.
 $repo=$tmp.'/repo';$remote=$tmp.'/remote.git';dirPrivate($repo);
 foreach([['git','init','--bare',$remote],['git','init','-b','main',$repo],['git','-C',$repo,'config','user.name','TED2 Test'],['git','-C',$repo,'config','user.email','test@example.invalid'],['git','-C',$repo,'remote','add','origin',$remote]] as $args)check(Process::run($args)['code']===0,'Git fixture '.implode(' ',array_slice($args,0,3)));
 file_put_contents($repo.'/source.txt','source only');file_put_contents($repo.'/.env','PRIVATE_ENV_SENTINEL');Process::run(['git','-C',$repo,'add','source.txt']);Process::run(['git','-C',$repo,'commit','-m','Source baseline']);file_put_contents($repo.'/staged.txt','unrelated staged change');Process::run(['git','-C',$repo,'add','staged.txt']);$indexBefore=Process::run(['git','-C',$repo,'diff','--cached'])['out'];
 $owner=['id'=>'original-user','username'=>'old-owner','role'=>'owner'];$publisher=new Publisher($s,$repo,true);$preview=$publisher->prepare($owner);check(is_file($publisher->directory.'/'.$preview['id'].'/site/index.html'),'publisher compiles private exact preview');$pushed=$publisher->push($owner,$preview['id']);check($pushed['ok']===true,'Git push succeeded without an extra password field');check($pushed['branch']==='gh-pages','only gh-pages receives public output');check($pushed['pages']['deployment']==='unverified','local test does not falsely claim deployment');check(trim(Process::run(['git','-C',$repo,'branch','--show-current'])['out'])==='main','working branch remains main');check(Process::run(['git','-C',$repo,'diff','--cached'])['out']===$indexBefore,'unrelated staged changes untouched');$tree=Process::run(['git','--git-dir='.$remote,'ls-tree','-r','--name-only','gh-pages'])['out'];check(!str_contains($tree,'.env')&&!str_contains($tree,'source.txt')&&!str_contains($tree,'staged.txt'),'private configuration and source excluded from public tree');check(str_contains($tree,'researchers/paulus-hamutenya/index.html'),'multi-page output pushed');
 rejects(fn()=>$publisher->push($owner,$preview['id']),409,'same preview cannot be pushed twice');$preview=$publisher->prepare($owner);$p=$s->get('people','paulus-hamutenya');$p['bio']='changed after preview';$s->replace('people',$p,$p['_version'],'fixture');rejects(fn()=>$publisher->push($owner,$preview['id']),409,'changed content invalidates reviewed preview');$r=['id'=>'old-researcher','username'=>'old-researcher','role'=>'researcher','researcher_id'=>'paulus-hamutenya'];rejects(fn()=>$publisher->prepare($r),403,'researcher cannot publish');
 echo "\n$checks core/migration/Git checks passed.\n";
}finally{if(isset($s))unset($s);Publisher::removeTree($tmp);}
