<?php
declare(strict_types=1);
namespace Ted2;
final class Application {
 public Store $store;public Auth $auth;public Records $records;
 public function __construct(){ $this->store=new Store();$this->auth=new Auth($this->store);$this->records=new Records($this->store); }
 private function body():array{$length=(int)($_SERVER['CONTENT_LENGTH']??0);ensure($length<=1024*1024,413,'Request is too large.');ensure(str_starts_with($_SERVER['CONTENT_TYPE']??'','application/json'),415,'Use JSON for this operation.');$raw=file_get_contents('php://input',false,null,0,1024*1024+1);ensure(strlen($raw)<=1024*1024,413,'Request is too large.');return decode($raw);}
 public function jsonResponse(mixed $value,int $status=200):never{http_response_code($status);header('Content-Type: application/json; charset=utf-8');header('Cache-Control: no-store');echo json($value);exit;}
 public function run():never{
  $method=$_SERVER['REQUEST_METHOD']??'GET';$path=rawurldecode(parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)??'/');
  header('X-Content-Type-Options: nosniff');header('Referrer-Policy: same-origin');header('X-Frame-Options: DENY');header("Permissions-Policy: camera=(), microphone=(), geolocation=()");
  header("Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' https: data:; media-src 'self'; connect-src 'self'; frame-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none'");
  if(Config::production())header('Strict-Transport-Security: max-age=31536000');
  ensure(!str_contains($path,"\0")&&!preg_match('#(^|/)\.\.?(/|$)#',$path),400,'Invalid request path.');
  $expected=parse_url(Config::origin(),PHP_URL_HOST).((parse_url(Config::origin(),PHP_URL_PORT))?':'.parse_url(Config::origin(),PHP_URL_PORT):'');ensure(strtolower($_SERVER['HTTP_HOST']??'')===strtolower($expected),400,'This host is not configured. Use the configured TED2_BASE_URL.');
  if($path==='/api/login'&&$method==='POST')$this->jsonResponse($this->auth->login($this->body()));
  if($path==='/api/logout'&&$method==='POST'){$this->auth->logout();$this->jsonResponse(['ok'=>true]);}
  if($path==='/api/anonymous/token'&&$method==='GET'){$time=time();$nonce=id();$payload=$time.'.'.$nonce;$this->jsonResponse(['token'=>$payload.'.'.hash_hmac('sha256',$payload,Config::secret())]);}
  if($path==='/api/anonymous'&&$method==='POST')$this->anonymous($this->body());
  if($path==='/admin'||$path==='/workspace'){
   header('Cache-Control: no-store');header('X-Robots-Tag: noindex, nofollow');header('Content-Type: text/html; charset=utf-8');$theme=(new PublicSite($this->store))->theme;
   echo '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>TED² · V6 Research Studio</title><link rel="stylesheet" href="/assets/site.css?v=6"><link rel="stylesheet" href="/assets/admin.css?v=6"><style>'.PublicSite::themeCss($theme).'</style><script defer src="/assets/admin.js?v=6"></script></head><body class="admin-body" data-theme="'.e($theme['preset']??'vintage').'"><a class="skip" href="#content">Skip to editor</a><div id="app"><p class="loading">Opening research studio…</p></div><div id="toast" role="status" hidden></div><dialog id="dialog"></dialog></body></html>';exit;
  }
  if(preg_match('#^/assets/(site\.css|site\.js|admin\.css|admin\.js)$#D',$path,$m)&&in_array($method,['GET','HEAD'],true)){Media::send(ROOT.'/public/assets/'.$m[1],str_ends_with($m[1],'.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8',private:false);}
  if(preg_match('#^/media/([a-f0-9]{32})$#D',$path,$m)&&in_array($method,['GET','HEAD'],true)){$row=$this->store->db->one('SELECT * FROM uploads WHERE id=?',[$m[1]]);ensure($row!==null,404,'Upload not found.');$media=new Media($this->store);ensure($media->canAccess($row,$this->auth->current(false)),404,'Upload is unavailable.');Media::send($media->path($row),$row['mime'],$row['original_name'],true);}
  if(preg_match('#^/public-media/[a-f0-9]{64}\.(jpg|png|webp|mp4|webm|pdf)$#D',$path)&&in_array($method,['GET','HEAD'],true)){$site=new PublicSite($this->store);foreach(['lab','institution','footer','favicon'] as $k)$site->branding($k);$file=$site->assets[ltrim($path,'/')]??null;ensure($file!==null,404,'Public asset not found.');Media::send($file,(new \finfo(FILEINFO_MIME_TYPE))->file($file),private:false);}
  if(str_starts_with($path,'/api/'))$this->api($method,$path);
  if($path==='/robots.txt'){header('Content-Type: text/plain');echo "User-agent: *\nDisallow: /admin\nDisallow: /workspace\nDisallow: /api/\nSitemap: ".Config::site()."/sitemap.xml\n";exit;}
  if($path==='/sitemap.xml'){header('Content-Type: application/xml');$site=new PublicSite($this->store);echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach($site->routes() as $r)echo '<url><loc>'.e(Config::site().'/'.$r).'</loc></url>';echo '</urlset>';exit;}
  ensure(in_array($method,['GET','HEAD'],true),405,'Method not allowed.');$site=new PublicSite($this->store);$html=$site->render(ltrim($path,'/'));header('Content-Type: text/html; charset=utf-8');header('Cache-Control: '.($path==='/questions/'?'no-store':'public, max-age=30'));if($method!=='HEAD')echo $html;exit;
 }
 private function api(string $method,string $path):never{
  $u=in_array($method,['GET','HEAD'],true)?$this->auth->current():$this->auth->write();
  if($path==='/api/bootstrap'&&$method==='GET'){
   $data=[];foreach(Schema::all() as $c=>$s){$data[$c]=array_values(array_filter($this->store->list($c),fn($p)=>$this->records->canRead($u,$c,$p)));}
   $refs=['people'=>[],'projects'=>[],'media'=>[]];foreach($refs as $c=>$_)foreach($this->store->list($c) as $p)if(Records::admin($u)||$this->records->canRead($u,$c,$p)||($c==='people'&&$p['visibility']==='public'))$refs[$c][]=array_intersect_key($p,array_flip(['id','name','title','scope','researcher_id','kind','file_id']));
   $this->jsonResponse(['version'=>VERSION,'user'=>$u,'schemas'=>Schema::all(),'records'=>$data,'references'=>$refs,'theme'=>(new PublicSite($this->store))->theme,'runtime'=>['language'=>'PHP','database_adapter'=>$this->store->db->adapter]]);
  }
  if(preg_match('#^/api/records/([a-z_]+)(?:/([a-z0-9-]+))?$#D',$path,$m)){$c=$m[1];$rid=$m[2]??null;Schema::get($c);
   if($method==='GET'){$rows=$rid?[$this->store->get($c,$rid)]:$this->store->list($c);$rows=array_values(array_filter($rows,fn($p)=>$p&&$this->records->canRead($u,$c,$p)));if($rid){ensure($rows!==[],404,'Record not available.');$this->jsonResponse($rows[0]);}$this->jsonResponse($rows);}
   if($method==='POST'&&!$rid)$this->jsonResponse($this->records->save($u,$c,$this->body()),201);
   if($method==='PUT'&&$rid)$this->jsonResponse($this->records->save($u,$c,$this->body(),$rid));
   if($method==='DELETE'&&$rid){$body=$this->body();ensure(is_int($body['_version']??null),428,'Current record version required.');$this->records->trash($u,$c,$rid,$body['_version']);$this->jsonResponse(['ok'=>true]);}
  }
  if(preg_match('#^/api/uploads/([a-z_]+)/([a-z0-9-]+)$#D',$path,$m)&&$method==='POST'){ensure(isset($_FILES['file'])&&!is_array($_FILES['file']['name']),422,'Choose one file.');$this->jsonResponse((new Media($this->store))->upload($u,$m[1],$m[2],$_FILES['file']),201);}
  if($path==='/api/trash'&&$method==='GET'){Auth::admin($u);$rows=$this->store->db->all("SELECT t.*,r.payload FROM trash t LEFT JOIN records r ON r.collection=t.collection AND r.id=t.id WHERE t.state='trashed' ORDER BY t.deleted_at DESC");foreach($rows as &$r){$p=decode($r['payload']??'{}');$r['title']=$p['title']??$p['name']??$p['label']??$p['question']??$r['id'];unset($r['payload']);}$this->jsonResponse($rows);}
  if(preg_match('#^/api/trash/([a-z_]+)/([a-z0-9-]+)/(restore|purge)$#D',$path,$m)&&$method==='POST'){
   Auth::admin($u);$body=$this->body();$c=$m[1];$rid=$m[2];$action=$m[3];ensure(!in_array($c,['settings','theme'],true),422,'Cannot delete site settings.');ensure($this->store->db->one("SELECT id FROM trash WHERE collection=? AND id=? AND state='trashed'",[$c,$rid])!==null,404,'Trashed record not found.');
   if($action==='purge'){$this->auth->password($u,(string)($body['password']??''));ensure(($body['confirm']??'')==='DELETE',422,'Type DELETE to confirm permanent removal.');}
   $this->store->db->tx(function()use($u,$c,$rid,$action){if($action==='restore'){$p=$this->store->get($c,$rid,true);ensure($p!==null,404,'Record no longer exists.');$this->records->references($c,$p,$p);$this->store->db->query('DELETE FROM trash WHERE collection=? AND id=?',[$c,$rid]);}else{
     ensure($c!=='people'||!$this->store->db->one('SELECT id FROM users WHERE researcher_id=?',[$rid]),409,'Reassign all linked accounts before purging this researcher.');
     $uploads=$this->store->db->all('SELECT * FROM uploads WHERE collection=? AND record_id=?',[$c,$rid]);foreach($uploads as $file){$path=(new Media($this->store))->path($file);if(is_file($path))unlink($path);}
     $this->store->db->query('DELETE FROM uploads WHERE collection=? AND record_id=?',[$c,$rid]);$this->store->db->query('DELETE FROM records WHERE collection=? AND id=?',[$c,$rid]);$this->store->db->query('DELETE FROM audit WHERE collection=? AND record_id=?',[$c,$rid]);$this->store->db->query("UPDATE trash SET state='purged' WHERE collection=? AND id=?",[$c,$rid]);}
    $this->store->audit($u['username'],$action,$c,$rid);
   });$this->jsonResponse(['ok'=>true]);
  }
  if($path==='/api/audit'&&$method==='GET'){Auth::admin($u);$this->jsonResponse($this->store->db->all('SELECT id,actor,action,collection,record_id,created_at FROM audit ORDER BY id DESC LIMIT 200'));}
  if($path==='/api/password'&&$method==='POST'){$b=$this->body();$this->auth->password($u,(string)($b['current']??''));$hash=Auth::hash((string)($b['password']??''));$this->store->db->tx(function()use($u,$hash){$this->store->db->query('UPDATE users SET password_hash=? WHERE id=?',[$hash,$u['id']]);$this->store->db->query('DELETE FROM sessions WHERE user_id=?',[$u['id']]);});$this->jsonResponse(['ok'=>true,'message'=>'Password changed. Sign in again.']);}
  if($path==='/api/users'&&$method==='GET'){Auth::owner($u);$this->jsonResponse($this->store->db->all('SELECT u.id,u.username,u.role,u.researcher_id,u.active,COALESCE(r.edit_profile,0) edit_profile,COALESCE(r.edit_research,0) edit_research FROM users u LEFT JOIN v6_rights r ON r.user_id=u.id ORDER BY username'));}
  if(($path==='/api/users'||preg_match('#^/api/users/([a-f0-9]{32})$#D',$path))&&in_array($method,['POST','PUT'],true))$this->userSave($u,$path,$this->body());
  if($path==='/api/responses'&&$method==='GET'){Auth::admin($u);$rows=$this->store->db->all('SELECT id,questionnaire_id,answers,created_at FROM responses ORDER BY created_at DESC LIMIT 200');foreach($rows as &$r)$r['answers']=decode($r['answers']);$this->jsonResponse($rows);}
  if(preg_match('#^/api/responses/([a-f0-9]{32})$#D',$path,$m)&&$method==='DELETE'){Auth::admin($u);$this->store->db->query('DELETE FROM responses WHERE id=?',[$m[1]]);$this->store->audit($u['username'],'delete-response','responses',$m[1]);$this->jsonResponse(['ok'=>true]);}
  if($path==='/api/literature/sync'&&$method==='POST'){$b=$this->body();$rid=Records::admin($u)?(($b['researcher_id']??null)?:null):$u['researcher_id'];$this->jsonResponse((new Literature($this->store))->sync($rid));}
  $publisher=new Publisher($this->store);
  if($path==='/api/publish/status'&&$method==='GET'){Auth::admin($u);$this->jsonResponse($publisher->status($_GET['commit']??null));}
  if($path==='/api/publish/prepare'&&$method==='POST'){$this->jsonResponse($publisher->prepare($u));}
  if($path==='/api/publish/push'&&$method==='POST'){$b=$this->body();ensure(($b['confirm']??false)===true,422,'Confirm the reviewed preview.');$this->jsonResponse($publisher->push($u,(string)($b['id']??'')));}
  if($path==='/api/publish/configure'&&$method==='POST'){$b=$this->body();ensure(($b['confirm']??'')==='CONFIGURE',422,'Confirm the Pages configuration change.');$this->jsonResponse($publisher->configure($u));}
  if(preg_match('#^/api/publish/preview/([a-f0-9]{32})/(.*)$#D',$path,$m)&&$method==='GET'){Auth::admin($u);$manifest=$publisher->manifest($u,$m[1]);$file=$m[2];if(str_ends_with($file,'/'))$file.='index.html';ensure(isset($manifest['files'][$file]),404,'Preview file not found.');$source=$publisher->directory.'/'.$m[1].'/site/'.$file;header('Cache-Control: no-store');header('X-Robots-Tag: noindex,nofollow');if(str_ends_with($file,'.html')){$prefix=rtrim((string)parse_url(Config::site(),PHP_URL_PATH),'/');$html=file_get_contents($source);$html=str_replace('="'.$prefix.'/','="/api/publish/preview/'.$m[1].'/',$html);$html=str_replace('data-base="'.$prefix.'"','data-base="/api/publish/preview/'.$m[1].'"',$html);header('Content-Type: text/html; charset=utf-8');echo $html;exit;}$mime=str_ends_with($file,'.css')?'text/css':(str_ends_with($file,'.js')?'text/javascript':(new \finfo(FILEINFO_MIME_TYPE))->file($source));Media::send($source,$mime,private:true);}
  throw new Problem(404,'API operation not found.');
 }
 private function userSave(array $u,string $path,array $b):never{
  Auth::owner($u);$rid=basename($path);$new=$path==='/api/users';if($new)$rid=id();$old=$new?null:$this->store->db->one('SELECT * FROM users WHERE id=?',[$rid]);ensure($new||$old!==null,404,'Account not found.');
  $name=strtolower(trim((string)($b['username']??'')));ensure(preg_match('/^[a-z0-9][a-z0-9._-]{2,59}$/D',$name)===1,422,'Use a lowercase username of 3–60 letters, digits, dots, underscores or hyphens.');$role=$b['role']??'';ensure(in_array($role,['owner','admin','researcher'],true),422,'Choose an account role.');$researcher=(string)($b['researcher_id']??'');if($role==='researcher')ensure($this->store->get('people',$researcher)!==null,422,'Choose the researcher for this account.');else $researcher='';
  $active=($b['active']??true)?1:0;$password=(string)($b['password']??'');$hash=$password!==''?Auth::hash($password):($old['password_hash']??'');ensure($hash!=='',422,'Set an initial password.');$duplicate=$this->store->db->one('SELECT id FROM users WHERE username=? AND id<>?',[$name,$rid]);ensure(!$duplicate,409,'This username already exists.');
  $this->store->db->tx(function()use($u,$rid,$old,$name,$role,$researcher,$active,$hash,$b){if($old&&$old['role']==='owner'&&$old['active']&&($role!=='owner'||!$active))ensure($this->store->db->one("SELECT COUNT(*) n FROM users WHERE role='owner' AND active=1")['n']>1,409,'The last active owner cannot be disabled or demoted.');if($old)$this->store->db->query('UPDATE users SET username=?,password_hash=?,role=?,researcher_id=?,active=? WHERE id=?',[$name,$hash,$role,$researcher,$active,$rid]);else $this->store->db->query('INSERT INTO users VALUES(?,?,?,?,?,?,?)',[$rid,$name,$hash,$role,$researcher,$active,utc()]);$this->store->db->query('INSERT INTO v6_rights VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET edit_profile=excluded.edit_profile,edit_research=excluded.edit_research',[$rid,!empty($b['edit_profile'])?1:0,!empty($b['edit_research'])?1:0]);$this->store->db->query('DELETE FROM sessions WHERE user_id=?',[$rid]);$this->store->audit($u['username'],$old?'update-account':'create-account','users',$rid,null,['username'=>$name,'role'=>$role,'researcher_id'=>$researcher,'active'=>$active]);});$this->jsonResponse(['ok'=>true,'id'=>$rid]);
 }
 private function anonymous(array $b):never{
  Auth::origin();$token=(string)($b['token']??'');ensure(preg_match('/^(\d{10})\.([a-f0-9]{32})\.([a-f0-9]{64})$/D',$token,$m)===1,403,'Reload the anonymous form.');ensure(hash_equals(hash_hmac('sha256',$m[1].'.'.$m[2],Config::secret()),$m[3])&&time()-(int)$m[1]>=2&&time()-(int)$m[1]<=3600,403,'Please wait a moment or reload the form.');ensure(empty($b['website']),422,'Submission rejected.');$ip=hash_hmac('sha256',gmdate('Y-m-d').'|'.($_SERVER['REMOTE_ADDR']??''),Config::secret());$this->auth->limit('anonymous:'.$ip,10,3600);
  $s=$this->store->get('settings','laboratory')??[];
  if(($b['kind']??'')==='question'){ensure(!empty($s['anonymous_enabled']),403,'Anonymous questions are currently closed.');$question=trim((string)($b['question']??''));ensure(strlen($question)>=8&&strlen($question)<=4000,422,'Write a question of 8–4000 characters.');$p=Schema::validate('questions',['id'=>id(),'visibility'=>'private','question'=>$question,'answer'=>'','researcher_id'=>'','status'=>'pending','order'=>0,'internal_notes'=>'','media_items'=>[]]);$this->store->insert('questions',$p,'anonymous');$this->jsonResponse(['ok'=>true,'message'=>'Received for moderation. Your question is not public yet.']);}
  ensure(($b['kind']??'')==='survey',422,'Unknown form type.');$survey=$this->store->get('questionnaires',(string)($b['questionnaire_id']??''));ensure($survey&&$survey['visibility']==='public'&&!empty($survey['open']),403,'This questionnaire is closed.');$answers=$b['answers']??[];ensure(is_array($answers)&&count($answers)<=100,422,'Invalid answer list.');$stored=[];$keys=[];
  foreach($this->store->list('survey_questions',true) as $q){if($q['questionnaire_id']!==$survey['id'])continue;$key=$q['id'];$keys[]=$key;$v=$answers[$key]??'';ensure(is_string($v)&&strlen($v)<=4000,422,'An answer is too long.');$v=trim($v);ensure(empty($q['required_answer'])||$v!=='',422,'Complete all required answers.');if($v!==''&&$q['kind']==='single-choice')ensure(in_array($v,$q['options'],true),422,'Invalid answer choice.');if($v!==''&&$q['kind']==='rating')ensure(in_array($v,['1','2','3','4','5'],true),422,'Choose a rating between 1 and 5.');$stored[]=['question_id'=>$key,'question'=>$q['label'],'answer'=>$v];}
  ensure($keys!==[]&&!array_diff(array_keys($answers),$keys),422,'Questionnaire questions changed. Reload the form.');$this->store->db->query('INSERT INTO responses VALUES(?,?,?,?)',[id(),$survey['id'],json($stored),utc()]);$this->jsonResponse(['ok'=>true,'message'=>'Your anonymous answers were received. They are visible only to authorised administrators.']);
 }
}
