<?php
declare(strict_types=1);
namespace Ted2;
/** Server-rendered pages and the GitHub Pages export share the same renderer. */
final class PublicSite {
 public array $data=[];public array $assets=[];public array $raw=[];public array $theme=[];public array $settings=[];private array $assetMap;public string $prefix;
 public function __construct(public Store $store,public bool $static=false){
  $this->prefix=$static?rtrim((string)parse_url(Config::site(),PHP_URL_PATH),'/'):'';$this->assetMap=decode(file_get_contents(ROOT.'/data/asset-map.json'));
  $store->db->tx(function(){foreach(array_keys(Schema::all()) as $c){$this->raw[$c]=[];foreach($this->store->list($c,true) as $p)$this->raw[$c][$p['id']]=$p;}},false);
  $this->project();$this->theme=$this->data['theme'][0]??[];$this->settings=$this->data['settings'][0]??[];
 }
 public function url(string $path=''):string{return $this->prefix.'/'.ltrim($path,'/');}
 public function publicId(string $c,string $rid):bool{return isset($this->raw[$c][$rid]);}
 public function asset(string $relative,string $root='data/assets'):string{$path=realpath(ROOT.'/'.$root.'/'.$relative);$allowed=realpath(ROOT.'/'.$root);if(!$path||!str_starts_with($path,$allowed.DIRECTORY_SEPARATOR)||!is_file($path))return '';$ext=strtolower(pathinfo($path,PATHINFO_EXTENSION));$key='public-media/'.hash_file('sha256',$path).'.'.$ext;$this->assets[$key]=$path;return $this->url($key);}
 public function upload(string $uid):string{$row=$this->store->db->one('SELECT * FROM uploads WHERE id=?',[$uid]);$m=new Media($this->store);if(!$row||!$m->canAccess($row,null))return '';$path=$m->path($row);$key='public-media/'.hash_file('sha256',$path).'.'.(Media::TYPES[$row['mime']]??'bin');$this->assets[$key]=$path;return $this->url($key);}
 private function project():void{
  foreach(Schema::all() as $c=>$schema){$this->data[$c]=[];foreach($this->raw[$c] as $p){
   if($c==='settings'&&$p['id']!=='laboratory'||$c==='theme'&&$p['id']!=='website')continue;
   if(in_array($c,['contacts','milestones','updates','achievements','acknowledgements','discoveries','sections','questions','questionnaires'],true)&&!empty($p['researcher_id'])&&!$this->publicId('people',$p['researcher_id']))continue;
   if($c==='media'){if(empty($p['approved'])||empty($p['file_id'])||($p['scope']??'review')==='review')continue;if(($p['scope']??'')==='researcher'&&!$this->publicId('people',$p['researcher_id']))continue;}
   if($c==='fields'&&!$this->publicId($p['target_collection'],$p['target_id']))continue;
   if($c==='questions'&&(($p['status']??'')!=='answered'||empty($p['answer'])))continue;
   if($c==='discoveries'&&empty($p['approved']))continue;
   if($c==='survey_questions'&&!$this->publicId('questionnaires',$p['questionnaire_id']))continue;
   $hidden=$p['hidden_fields']??[];$out=['id'=>$p['id']];foreach($schema['fields'] as $f){$k=$f['key'];if(!$f['public']||in_array($f['type'],['image','document','asset'],true))continue;if(in_array($k,$hidden,true)){$out[$k]=Schema::default($f);continue;}$v=$p[$k]??Schema::default($f);if($f['relation']){$v=$f['type']==='multi'?array_values(array_filter($v??[],fn($rid)=>$this->publicId($f['relation'],$rid))):($v&&$this->publicId($f['relation'],$v)?$v:'');}$out[$k]=$v;}
   if($c==='people'){$out['photo_url']='';if(!in_array('photo_url',$hidden,true)&&($p['photo_permission']??'')==='approved'){$photo=$this->upload($p['photo_upload_id']??'');if(!$photo&&isset($this->assetMap['portraits'][$p['bundled_portrait']??'']))$photo=$this->asset($this->assetMap['portraits'][$p['bundled_portrait']]);$out['photo_url']=$photo?:($p['photo_url']??'');}}
   if($c==='settings'&&!in_array('hero_image_url',$hidden,true)&&($p['hero_permission']??'')==='approved'){$image=$this->upload($p['hero_upload_id']??'');if(!$image&&isset($this->assetMap['homepage'][$p['bundled_hero']??'']))$image=$this->asset($this->assetMap['homepage'][$p['bundled_hero']]);if($image)$out['hero_image_url']=$image;}
   if($c==='theme')foreach(['logo_upload_id'=>'logo_url','institution_logo_id'=>'institution_logo_url','footer_logo_id'=>'footer_logo_url','favicon_id'=>'favicon_url'] as $field=>$output){$out[$output]=$this->upload($p[$field]??'');}
   if($c==='media'){$out['asset_url']=$this->upload($p['file_id']);if(!$out['asset_url'])continue;$row=$this->store->db->one('SELECT original_name,mime FROM uploads WHERE id=?',[$p['file_id']]);$out['mime']=$row['mime'];$out['display_filename']=Media::filename($p['display_filename']?:$row['original_name'],Media::TYPES[$row['mime']]);}
   if(in_array($c,['achievements','publications'],true)&&!empty($p['document_public'])){$out['document_url']=$this->upload($p['document_id']??'');if($c==='achievements'&&empty($p['document_id'])&&isset($this->assetMap['certificates'][$p['certificate_key']??''])){$a=$this->assetMap['certificates'][$p['certificate_key']];$out['document_url']=$this->asset($a['pdf']);$out['certificate_preview']=$this->asset($a['preview']);}}
   $this->data[$c][]=$out;
  }}
  $validMedia=array_column($this->data['media'],'id');foreach($this->data as &$rows)foreach($rows as &$p)if(isset($p['media_items']))$p['media_items']=array_values(array_intersect($p['media_items'],$validMedia));unset($rows,$p);
  usort($this->data['media'],fn($a,$b)=>(($a['order']??0)<=>($b['order']??0))?:strnatcasecmp($a['title'],$b['title']));
  usort($this->data['people'],function($a,$b){$pa=(int)($a['priority']??0);$pb=(int)($b['priority']??0);if($pa||$pb){$cmp=($pa?:PHP_INT_MAX)<=>($pb?:PHP_INT_MAX);if($cmp)return $cmp;}return strnatcasecmp(($a['sort_name']??'')?:$a['name'],($b['sort_name']??'')?:$b['name']);});
 }
 public function find(string $c,string $id):?array{foreach($this->data[$c]??[] as $p)if($p['id']===$id)return $p;return null;}
 public function branding(string $kind):string{$map=['lab'=>['logo_url','ted2-wordmark.png'],'institution'=>['institution_logo_url','unam-logo.png'],'footer'=>['footer_logo_url','ted2-wordmark.png'],'favicon'=>['favicon_url','ted2-icon.png']];return ($this->theme[$map[$kind][0]]??'')?:$this->asset($map[$kind][1],'data/branding');}
 public static function themeCss(array $t):string{
  $defaults=['primary'=>'#244d3e','accent'=>'#a88451','background'=>'#f5f3eb','surface'=>'#ffffff','text_color'=>'#1d3028','muted_color'=>'#616c63','border_color'=>'#d9dfd4'];$css=':root{';foreach($defaults as $k=>$v){$color=$t[$k]??$v;if(!preg_match('/^#[\da-f]{6}$/i',$color))$color=$v;$css.='--'.str_replace('_','-',$k).':'.$color.';';}
  $fonts=['serif'=>'Georgia,"Times New Roman",serif','sans'=>'system-ui,-apple-system,"Segoe UI",sans-serif','humanist'=>'"Trebuchet MS",Arial,sans-serif'];$css.='--heading-font:'.($fonts[$t['heading_font']??'serif']??$fonts['serif']).';--body-font:'.($fonts[$t['body_font']??'sans']??$fonts['sans']).';';foreach(['font_size'=>[14,22,16,'font-size'],'content_width'=>[960,1600,1200,'content-width'],'corner_radius'=>[0,28,16,'radius']] as $k=>[$min,$max,$default,$name])$css.='--'.$name.':'.max($min,min($max,(int)($t[$k]??$default))).'px;';return $css.'}';
 }
 public function head(string $title,string $description,string $path,array $structured=[]):string{
  $canonical=Config::site().'/'.ltrim($path,'/');$verification=!empty($this->settings['search_console_verification'])?'<meta name="google-site-verification" content="'.e($this->settings['search_console_verification']).'">':'';$jsonld=$structured?'<script type="application/ld+json">'.json_encode($structured,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE).'</script>':'';
  return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'.e($title).' | TED² Laboratory</title><meta name="description" content="'.e($description).'"><link rel="canonical" href="'.e($canonical).'"><meta property="og:title" content="'.e($title).'"><meta property="og:description" content="'.e($description).'"><meta property="og:url" content="'.e($canonical).'"><meta name="theme-color" content="'.e($this->theme['primary']??'#244d3e').'"><link rel="icon" href="'.e($this->branding('favicon')).'"><link rel="stylesheet" href="'.$this->url('assets/site.css').'?v=6"><style>'.self::themeCss($this->theme).'</style>'.$verification.$jsonld.'<script defer src="'.$this->url('assets/site.js').'?v=6"></script></head><body data-base="'.e($this->prefix).'" data-theme="'.e($this->theme['preset']??'vintage').'" data-density="'.e($this->theme['density']??'comfortable').'"><a class="skip" href="#main">Skip to content</a>';
 }
 public function header():string{
  $t=$this->theme;$s=$this->settings;$html='<header class="site-header band-'.e($t['header_band']??'none').' align-'.e($t['header_alignment']??'balanced').'"><div class="container brand-row"><a class="brand" href="'.$this->url().'">';if($t['show_lab_logo']??true)$html.='<img src="'.e($this->branding('lab')).'" alt="TED² laboratory" width="230" height="78">';$html.='<span><strong>'.e($s['short_name']?:'TED² Laboratory').'</strong><small>'.e($t['brand_tagline']?:($s['institution']??'University of Namibia')).'</small></span></a>';
  if($t['show_institution_logo']??true)$html.='<img class="institution-logo" src="'.e($this->branding('institution')).'" alt="Institution logo" width="120" height="70">';$html.='<button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button></div><nav id="main-nav" class="container main-nav" aria-label="Main navigation"><a href="'.$this->url().'">Home</a>';
  $items=['researchers'=>'Researchers','research'=>'Research','publications'=>'Publications','activity'=>'Activity','gallery'=>'Gallery','questions'=>'Questions','collaborators'=>'Collaborations','funders'=>'Funders'];foreach($items as $url=>$label)if(!in_array($url,$t['hidden_navigation']??[],true))$html.='<a href="'.$this->url($url.'/').'">'.e($label).'</a>';foreach($this->data['sections'] as $p)if($p['location']==='standalone-page'&&!empty($p['navigation']))$html.='<a href="'.$this->url('pages/'.$p['id'].'/').'">'.e($p['nav_label']?:$p['title']).'</a>';return $html.'</nav></header>';
 }
 public function footer():string{$t=$this->theme;$s=$this->settings;$h='<footer class="site-footer band-'.e($t['footer_band']??'none').' align-'.e($t['footer_alignment']??'balanced').'"><div class="container footer-grid"><div>';if($t['show_footer_logo']??true)$h.='<img class="footer-logo" src="'.e($this->branding('footer')).'" alt="TED² laboratory logo" width="230" height="78">';$h.='<p>'.e($t['footer_text']?:($s['title']??'TED² Laboratory')).'</p><p>'.nl2br(e($s['address']??'')).'</p></div><div><a href="'.$this->url('sources/').'">Sources & image credits</a><a href="'.$this->url('questions/').'">Questions & privacy</a><a href="'.$this->url('researchers/').'">Researcher directory</a><a href="#main">Back to top ↑</a></div></div><div class="container footer-note">Public content is published by the laboratory. Unpublished research and private contact information are not part of this website.</div></footer></body></html>';return $h;}
 public function paragraph(string $text):string{if($text==='')return '';return implode('',array_map(fn($p)=>'<p>'.nl2br(e($p)).'</p>',preg_split('/\R\s*\R/',trim($text))));}
 public function linkPerson(string $id):string{$p=$this->find('people',$id);return $p?'<a href="'.$this->url('researchers/'.$p['id'].'/').'">'.e($p['name']).'</a>':'';}
 public function mediaCards(array $ids):string{$h='<div class="media-grid">';foreach($ids as $id){$m=$this->find('media',$id);if(!$m)continue;$h.='<figure class="media-card">';$src=e($m['asset_url']);if($m['kind']==='image')$h.='<a href="'.$src.'"><img loading="lazy" decoding="async" src="'.$src.'" alt="'.e($m['alt']?:$m['title']).'" width="640" height="480"></a>';elseif($m['kind']==='video')$h.='<video controls playsinline preload="none" aria-label="'.e($m['title']).'"><source src="'.$src.'" type="'.e($m['mime']).'">Video playback is not available. <a href="'.$src.'">Download the recording</a>.</video>';else $h.='<a class="document-cover" href="'.$src.'" download="'.e($m['display_filename']).'">PDF · '.e($m['title']).'</a>';$h.='<figcaption><h3>'.e($m['title']).'</h3>'.$this->paragraph($m['caption']??'').'<small>'.e($m['credit']??'').'</small><a class="download-link" download="'.e($m['display_filename']).'" href="'.$src.'">Download '.e($m['display_filename']).'</a>';if(!empty($m['transcript']))$h.='<details><summary>Transcript</summary>'.$this->paragraph($m['transcript']).'</details>';$h.='</figcaption></figure>'; }return $h.'</div>';}
 public function recordCard(string $c,array $p):string{
  $title=$p['title']??$p['name']??$p['label']??'Research update';$path='records/'.$c.'/'.$p['id'].'/';$h='<article class="card"><span class="eyebrow">'.e(Schema::get($c)['label']).'</span><h3><a href="'.$this->url($path).'">'.e($title).'</a></h3>';$text=$p['summary']??$p['description']??$p['text']??$p['detail']??'';if($text)$h.='<p>'.e(self::excerpt($text,230)).'</p>';foreach(['date','start_date','end_date','stage','status'] as $k)if(!empty($p[$k]))$h.='<span class="tag">'.e(str_replace('-',' ',$p[$k])).'</span>';if(!empty($p['researcher_id']))$h.='<p>'.$this->linkPerson($p['researcher_id']).'</p>';return $h.'</article>';
 }
 public static function excerpt(string $t,int $max=180):string{$t=preg_replace('/\s+/u',' ',trim($t));return strlen($t)>$max?preg_replace('/\s+\S*$/u','',substr($t,0,$max)).'…':$t;}
 public function personCard(array $p):string{$url=$this->url('researchers/'.$p['id'].'/');$photo=!empty($p['photo_url'])?'<img loading="lazy" decoding="async" src="'.e($p['photo_url']).'" alt="'.e($p['name']).'" width="360" height="400">':'<div class="initials">'.e(preg_replace('/[^A-Z]/','',$p['name'])).'</div>';return '<article class="person-card"><a class="portrait" href="'.$url.'">'.$photo.'</a><div><span class="eyebrow">'.e($p['group']??'Researcher').'</span><h3><a href="'.$url.'">'.e($p['name']).'</a></h3><p>'.e($p['role']??'').'</p><a class="text-link" href="'.$url.'">Profile & research →</a></div></article>';}
 public function section(array $p):string{$h='<section class="custom-section"><div class="section-heading"><span class="eyebrow">'.e($p['eyebrow']??'').'</span><h2>'.e($p['title']).'</h2></div><div class="layout-'.e($p['layout']??'text').'"><div class="prose">'.$this->paragraph($p['body']??'').'</div>'.$this->mediaCards($p['media_items']??[]).'</div></section>';return $h;}
 public function extras(string $c,array $p):string{$h='';$fs=array_filter($this->data['fields'],fn($f)=>$f['target_collection']===$c&&$f['target_id']===$p['id']);usort($fs,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));if($fs){$h.='<dl class="details-grid">';foreach($fs as $f)$h.='<div><dt>'.e($f['label']).'</dt><dd>'.nl2br(e($f['value'])).'</dd></div>';$h.='</dl>';}return $h.$this->mediaCards($p['media_items']??[]);}
 public function spotlight():string{$items=[];foreach($this->data['announcements'] as $p)if(!empty($p['homepage'])&&(!$p['end_date']||$p['end_date']>=gmdate('Y-m-d')))$items[]=['announcements',$p];foreach($this->data['achievements'] as $p)if(!empty($p['homepage']))$items[]=['achievements',$p];foreach($this->data['updates'] as $p)$items[]=['updates',$p];foreach($this->data['projects'] as $p)if($p['public_progress']!==null)$items[]=['projects',$p];if(!$items)return '';$h='<section class="spotlight" aria-label="Laboratory notice board" data-carousel data-autoplay="'.(!empty($this->theme['rotate_spotlight'])?'yes':'no').'"><div class="spotlight-top"><span class="eyebrow">Laboratory notice board</span><div><button data-carousel-prev aria-label="Previous notice">←</button><button data-carousel-pause>Pause</button><button data-carousel-next aria-label="Next notice">→</button></div></div>';
  foreach($items as $i=>[$c,$p]){$h.='<div class="notice-slide" data-slide'.($i?' hidden':'').'><span class="tag">'.e($c==='announcements'?($p['kind']??'Alert'):Schema::get($c)['label']).'</span><h2><a href="'.$this->url('records/'.$c.'/'.$p['id'].'/').'">'.e($p['title']).'</a></h2><p>'.e(self::excerpt($p['description']??$p['summary']??$p['text']??'',280)).'</p>';if(!empty($p['start_date']))$h.='<p class="notice-date">'.e($p['start_date']).(!empty($p['end_date'])?' — '.e($p['end_date']):'').'</p>';if(($p['date_status']??'')==='date-conflict')$h.='<p class="notice-evidence">Date confirmation pending. '.e($p['evidence_note']??'').'</p>';if($c==='projects')$h.='<p>Approved public progress: '.e($p['public_progress']).'%</p>';$h.='</div>';}$h.='<p class="carousel-count" data-carousel-count>1 / '.count($items).'</p></section>';return $h;
 }
 public function home():string{
  $s=$this->settings;$t=$this->theme;$blocks=$t['home_blocks']??['hero','alerts','research','people','recognition','contacts','leadership','questions'];$h='';foreach($blocks as $block){switch($block){
   case 'hero':$h.='<section class="hero layout-'.e($t['hero_layout']??'photo-right').'"><div><span class="eyebrow">'.e($s['hero_eyebrow']?:'TED² · University of Namibia').'</span><h1>'.e($s['hero_title']??$s['title']??'TED² Laboratory').'</h1><div class="lead">'.$this->paragraph($s['hero_intro']??'').'</div><div class="actions"><a class="button" href="'.$this->url('researchers/').'">Meet our researchers</a><a class="button secondary" href="'.$this->url('research/').'">Explore the research</a></div></div>';if(($t['hero_layout']??'')!=='text-only'&&!empty($s['hero_image_url']))$h.='<figure class="hero-photo'.(!empty($s['hero_motion'])?' arrival':'').'"><img src="'.e($s['hero_image_url']).'" alt="'.e($s['hero_image_alt']?:'Laboratory research activity').'" width="720" height="760"><figcaption>'.e($s['hero_image_caption']??'').'</figcaption></figure>';$h.='</section>';break;
   case 'alerts':$h.=$this->spotlight();break;
   case 'research':$h.='<section><div class="section-heading"><span class="eyebrow">Research capabilities</span><h2>'.e($s['research_title']?:'The science behind our laboratory').'</h2></div><div class="card-grid">';$rows=$this->data['capabilities'];usort($rows,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));foreach($rows as $p)$h.='<article class="card"><h3>'.e($p['title']).'</h3>'.$this->paragraph($p['text']).'</article>';$h.='</div></section>';break;
   case 'people':$h.='<section><div class="section-heading"><span class="eyebrow">People & collaboration</span><h2>'.e($s['people_title']?:'Researchers').'</h2></div><div class="people-grid">';foreach($this->data['people'] as $p)$h.=$this->personCard($p);$h.='</div></section>';break;
   case 'recognition':$rows=array_filter($this->data['achievements'],fn($p)=>!empty($p['homepage']));if($rows){$h.='<section><h2>Recognition</h2><div class="card-grid">';foreach($rows as $p)$h.=$this->recordCard('achievements',$p);$h.='</div></section>';}break;
   case 'contacts':$h.='<section><h2>'.e($s['contacts_title']?:'Contact the laboratory').'</h2><div class="contact-grid">';if(!empty($s['contact_email']))$h.='<article class="card"><h3>'.e($s['contact_name']?:'Laboratory enquiries').'</h3><a href="mailto:'.e($s['contact_email']).'">'.e($s['contact_email']).'</a>'.$this->paragraph($s['address']??'').'</article>';foreach($this->data['contacts'] as $p)if(!empty($p['show_homepage']))$h.=$this->contact($p);$h.='</div></section>';break;
   case 'leadership':$rows=array_values(array_filter($this->data['acknowledgements'],fn($p)=>!empty($p['homepage'])));usort($rows,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));if($rows){$h.='<section><h2>Leadership & acknowledgements</h2><div class="card-grid">';foreach($rows as $p)$h.='<article class="card"><span class="eyebrow">'.e($p['label']).'</span><h3>'.$this->linkPerson($p['researcher_id']).'</h3>'.$this->paragraph($p['description']??'').'</article>';$h.='</div></section>';}break;
   case 'questions':$h.='<section class="question-banner"><div><span class="eyebrow">A space for questions</span><h2>Ask. Reflect. Contribute.</h2><p>Explore answered questions or contribute without providing your name.</p></div><a class="button" href="'.$this->url('questions/').'">Questions & questionnaires →</a></section>';break;
   case 'gallery':$h.='<section><h2>Laboratory gallery</h2>'.$this->mediaCards(array_column(array_filter($this->data['media'],fn($m)=>$m['scope']==='laboratory'),'id')).'</section>';break;
  }
  $positions=['hero'=>'after-hero','alerts'=>'after-alerts','research'=>'after-research'];if(isset($positions[$block]))$h.=$this->homeSections($positions[$block]);
 }return $h.$this->homeSections('before-footer').$this->extras('settings',$s);}
 private function homeSections(string $position):string{$rows=array_filter($this->data['sections'],fn($s)=>$s['location']==='homepage'&&$s['position']===$position);usort($rows,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));return implode('',array_map($this->section(...),$rows));}
 public function contact(array $p):string{$v=e($p['value']);if($p['kind']==='email')$v='<a href="mailto:'.$v.'">'.$v.'</a>';elseif($p['kind']==='telephone')$v='<a href="tel:'.e(preg_replace('/[^+0-9]/','',$p['value'])).'">'.$v.'</a>';elseif($p['kind']==='website'&&safeUrl($p['value']))$v='<a href="'.$v.'" rel="noopener">'.$v.'</a>';return '<article class="card"><h3>'.e($p['label']).'</h3><p>'.nl2br($v).'</p>'.(!empty($p['researcher_id'])?'<p>'.$this->linkPerson($p['researcher_id']).'</p>':'').'</article>';}
 public function researcher(array $p):string{
  $h='<section class="profile-heading"><div class="portrait">'.(!empty($p['photo_url'])?'<img src="'.e($p['photo_url']).'" alt="'.e($p['name']).'" width="480" height="560">':'').'</div><div><span class="eyebrow">Researcher profile</span><h1>'.e($p['name']).'</h1><p class="lead">'.e($p['role']??'').'</p><p>'.e($p['affiliation']??'').'</p><p>'.e($p['department']??'').'</p><div class="actions">';foreach(['scholar_url'=>'Google Scholar','orcid_url'=>'ORCID','researchgate_url'=>'ResearchGate','website'=>'Website'] as $k=>$l)if(!empty($p[$k]))$h.='<a class="button secondary" href="'.e($p[$k]).'" rel="noopener">'.$l.'</a>';$h.='</div></div></section><section class="prose"><h2>Biography & research</h2>'.$this->paragraph($p['bio']??'').$this->paragraph($p['work']??'');if($p['topics']??[])$h.='<div class="tags">'.implode('',array_map(fn($x)=>'<span class="tag">'.e($x).'</span>',$p['topics'])).'</div>';$h.=$this->paragraph($p['note']??'').'</section>';
  foreach(['qualifications','public_email','public_phone'] as $k)if(!empty($p[$k]))$h.='<p><strong>'.e(ucwords(str_replace('_',' ',$k))).':</strong> '.e($p[$k]).'</p>';
  foreach(['publications','projects','manuscripts','milestones','achievements','updates','announcements','collaborations','discoveries'] as $c){$rows=array_filter($this->data[$c],fn($r)=>Records::researcherOf($c,$r)===$p['id']||in_array($p['id'],$r['people']??[],true));if($rows){$h.='<section><h2>'.e(Schema::get($c)['label']).'</h2><div class="card-grid">';foreach($rows as $r)$h.=$this->recordCard($c,$r);$h.='</div></section>';}}
  $contacts=array_filter($this->data['contacts'],fn($r)=>$r['researcher_id']===$p['id']);if($contacts){$h.='<section><h2>Contact</h2><div class="contact-grid">';foreach($contacts as $r)$h.=$this->contact($r);$h.='</div></section>';}
  $sections=array_filter($this->data['sections'],fn($r)=>$r['location']==='researcher-profile'&&$r['researcher_id']===$p['id']);usort($sections,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));foreach($sections as $r)$h.=$this->section($r);
  $used=$p['media_items']??[];foreach($sections as $section)$used=array_merge($used,$section['media_items']??[]);$h.=$this->extras('people',$p);$ids=array_column(array_filter($this->data['media'],fn($m)=>$m['scope']==='researcher'&&$m['researcher_id']===$p['id']&&!in_array($m['id'],$used,true)),'id');if($ids)$h.='<section><h2>Research media & documents</h2>'.$this->mediaCards($ids).'</section>';return $h;
 }
 public function recordDetail(string $c,array $p):string{
  $h='<section><span class="eyebrow">'.e(Schema::get($c)['label']).'</span><h1>'.e($p['title']??$p['name']??$p['label']).'</h1>';
  foreach(['researcher_id','lead_id'] as $k)if(!empty($p[$k]))$h.='<p>'.$this->linkPerson($p[$k]).'</p>';if(!empty($p['people']))$h.='<p>'.implode(' · ',array_filter(array_map($this->linkPerson(...),$p['people']))).'</p>';
  if($c==='publications')$h.='<p>'.e(implode(', ',$p['authors']??[])).'</p><p>'.e(($p['venue']??'').' · '.($p['year']??'')).'</p><p class="tag">'.e($p['type']??'').'</p>';
  foreach(['summary','description','text','detail','body','note','evidence_note'] as $k)if(!empty($p[$k]))$h.='<div class="prose">'.$this->paragraph($p[$k]).'</div>';
  $h.='<dl class="details-grid">';foreach(['date','start_date','end_date','due_date','date_status','host','location','stage','status','public_progress','evidence','period','partner','award_reference','year','journal','authors'] as $k)if(isset($p[$k])&&$p[$k]!==''&&$p[$k]!==null)$h.='<div><dt>'.e(ucwords(str_replace('_',' ',$k))).'</dt><dd>'.e(is_array($p[$k])?implode(', ',$p[$k]):$p[$k]).'</dd></div>';$h.='</dl><div class="actions">';foreach(['doi'=>'DOI','source_url'=>'Source record','website'=>'Website','official_url'=>'Official host','website'=>'Website'] as $k=>$label){if(!empty($p[$k])){$url=$k==='doi'?'https://doi.org/'.$p[$k]:$p[$k];if(safeUrl($url))$h.='<a class="button secondary" href="'.e($url).'">'.$label.' ↗</a>';}}$h.='</div>';
  if(!empty($p['certificate_preview']))$h.='<img class="certificate" loading="lazy" src="'.e($p['certificate_preview']).'" alt="Certificate preview">';if(!empty($p['document_url']))$h.='<p><a class="button" href="'.e($p['document_url']).'" download>Download approved document</a></p>';
  return $h.$this->extras($c,$p).'</section>';
 }
 public function questions():string{
  $h='<section><span class="eyebrow">Anonymous contributions</span><h1>Questions & answers</h1><p class="lead">No name or email is required. Questions are moderated before appearing here.</p><details><summary>Privacy & how responses are used</summary>'.$this->paragraph($this->settings['privacy_notice']??'').'</details>';
  foreach($this->data['questions'] as $q)$h.='<details class="question-card"><summary>'.e($q['question']).'</summary>'.$this->paragraph($q['answer']).'</details>';
  $site=$this->settings['submission_site']??'';if($this->static){if(safeUrl($site,true)&&$site!=='')$h.='<a class="button" href="'.e(rtrim($site,'/').'/questions/').'">Submit anonymously on our secure research site</a>';else $h.='<p class="notice-evidence">Online submissions are not connected yet. Published questions remain available here.</p>';}
  else{if(!empty($this->settings['anonymous_enabled']))$h.='<form class="anonymous-form" data-anonymous="question"><h2>Ask a question</h2><label>Question<textarea name="question" required maxlength="4000" rows="5"></textarea></label><label class="honeypot" aria-hidden="true">Leave blank<input name="website" tabindex="-1" autocomplete="off"></label><button class="button">Send for moderation</button><p role="status"></p></form>';
   foreach($this->data['questionnaires'] as $survey){if(empty($survey['open']))continue;$h.='<form class="anonymous-form" data-anonymous="survey" data-survey="'.e($survey['id']).'"><h2>'.e($survey['title']).'</h2>'.$this->paragraph($survey['description']??'');$qs=array_filter($this->data['survey_questions'],fn($q)=>$q['questionnaire_id']===$survey['id']);usort($qs,fn($a,$b)=>($a['order']??0)<=>($b['order']??0));foreach($qs as $q){$req=!empty($q['required_answer'])?' required':'';$name='q_'.$q['id'];$h.='<label>'.e($q['label']);if($q['kind']==='single-choice'||$q['kind']==='rating'){$options=$q['kind']==='rating'?['1','2','3','4','5']:$q['options'];$h.='<select name="'.e($name).'"'.$req.'><option value="">Choose</option>';foreach($options as $o)$h.='<option>'.e($o).'</option>';$h.='</select>';}elseif($q['kind']==='long-text')$h.='<textarea name="'.e($name).'" rows="4" maxlength="4000"'.$req.'></textarea>';else $h.='<input name="'.e($name).'" maxlength="1000"'.$req.'>';$h.='</label>';}$h.='<label class="honeypot" aria-hidden="true">Leave blank<input name="website" tabindex="-1"></label><button class="button">Submit answers anonymously</button><p role="status"></p></form>';}
  }return $h.'</section>';
 }
 public function routes():array{$routes=['','researchers/','research/','publications/','activity/','gallery/','questions/','collaborators/','funders/','sources/','pipeline/'];foreach($this->data['people'] as $p)$routes[]='researchers/'.$p['id'].'/';foreach(['publications','projects','manuscripts','milestones','achievements','updates','announcements','collaborations','funders','discoveries'] as $c)foreach($this->data[$c] as $p)$routes[]='records/'.$c.'/'.$p['id'].'/';foreach($this->data['sections'] as $p)if($p['location']==='standalone-page')$routes[]='pages/'.$p['id'].'/';return $routes;}
 public function render(string $path):string{
  $path=ltrim($path,'/');$title='Research & discovery';$desc=self::excerpt($this->settings['hero_intro']??'TED² laboratory research, people and publications.');$structured=[];$h='';
  if($path===''){$h=$this->home();$title=$this->settings['title']??'TED² Laboratory';$structured=['@context'=>'https://schema.org','@type'=>'ResearchOrganization','name'=>$title,'url'=>Config::site().'/'];}
  elseif(preg_match('#^researchers/([a-z0-9-]+)/$#D',$path,$m)){$p=$this->find('people',$m[1]);ensure($p!==null,404,'Researcher not found.');$h=$this->researcher($p);$title=$p['name'];$desc=self::excerpt($p['bio']?:$p['work']?:$p['role']);$structured=['@context'=>'https://schema.org','@type'=>'ProfilePage','mainEntity'=>['@type'=>'Person','name'=>$p['name'],'description'=>$desc,'url'=>Config::site().'/'.$path,'sameAs'=>array_values(array_filter(array_intersect_key($p,array_flip(['scholar_url','orcid_url','researchgate_url','website']))))]];}
  elseif(preg_match('#^records/([a-z_]+)/([a-z0-9-]+)/$#D',$path,$m)){$p=$this->find($m[1],$m[2]);ensure($p!==null&&in_array($path,$this->routes(),true),404,'Public record not found.');$h=$this->recordDetail($m[1],$p);$title=$p['title']??$p['name'];$desc=self::excerpt($p['summary']??$p['description']??$title);}
  elseif(preg_match('#^pages/([a-z0-9-]+)/$#D',$path,$m)){$p=$this->find('sections',$m[1]);ensure($p&&$p['location']==='standalone-page',404,'Page not found.');$h=$this->section($p);$title=$p['title'];}
  elseif($path==='questions/'){$h=$this->questions();$title='Questions & questionnaires';}
  elseif($path==='researchers/'){$title='Researchers & collaborators';$h='<section><h1>'.$title.'</h1><p class="lead">Prioritised researchers appear first; the remaining directory is alphabetical by surname.</p><label class="search-label">Find a researcher<input type="search" data-filter placeholder="Name or research area"></label><div class="people-grid" data-filter-grid>';foreach($this->data['people'] as $p)$h.=$this->personCard($p);$h.='</div></section>';}
  elseif($path==='gallery/'){$title='Laboratory gallery';$h='<section><h1>'.$title.'</h1><p>General laboratory photographs, recordings and documents. Researcher-owned files are on the corresponding profiles.</p>'.$this->mediaCards(array_column(array_filter($this->data['media'],fn($m)=>$m['scope']==='laboratory'),'id')).'</section>';}
  elseif($path==='research/'){$title='Research programmes & progress';$h='<section><h1>'.$title.'</h1><div class="card-grid">';foreach($this->data['projects'] as $p)$h.=$this->recordCard('projects',$p);$h.='</div><h2>Research capabilities</h2><div class="card-grid">';foreach($this->data['capabilities'] as $p)$h.='<article class="card"><h3>'.e($p['title']).'</h3>'.$this->paragraph($p['text']).'</article>';$h.='</div></section>';}
  elseif($path==='sources/'){$title='Sources & credits';$h='<section><h1>'.$title.'</h1><div class="card-grid">';foreach($this->data['sources'] as $p)$h.='<article class="card"><h3>'.e($p['title']).'</h3>'.$this->paragraph($p['note']??'').(!empty($p['url'])?'<a href="'.e($p['url']).'">View source ↗</a>':'').'</article>';$h.='</div></section>';}
  else{$lists=['publications/'=>['Publications',['publications']],'activity/'=>['Laboratory activity',['announcements','achievements','updates']],'collaborators/'=>['Collaborations',['collaborations']],'funders/'=>['Funders & support',['funders']],'pipeline/'=>['Research pipeline',['manuscripts']]];ensure(isset($lists[$path]),404,'Page not found.');[$title,$collections]=$lists[$path];$h='<section><h1>'.e($title).'</h1><div class="card-grid">';foreach($collections as $c)foreach($this->data[$c] as $p)$h.=$this->recordCard($c,$p);$h.='</div></section>';}
  return $this->head($title,$desc,$path,$structured).$this->header().'<main id="main" class="container">'.$h.'</main>'.$this->footer();
 }
 public function build(string $directory):array{
  dirPrivate($directory);$files=[];foreach($this->routes() as $route){$path=$route.'index.html';$bytes=$this->render($route);atomic($directory.'/'.$path,$bytes);$files[]=$path;}
  foreach(['site.css','site.js'] as $name){dirPrivate($directory.'/assets');copy(ROOT.'/public/assets/'.$name,$directory.'/assets/'.$name);$files[]='assets/'.$name;}
  $total=0;foreach($this->assets as $key=>$source){$total+=filesize($source);ensure($total<=400*1024*1024,413,'Public media exceeds 400 MiB. Reduce recordings before publishing.');dirPrivate(dirname($directory.'/'.$key));ensure(copy($source,$directory.'/'.$key),500,'Could not copy public media.');$files[]=$key;}
  $sitemap='<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';foreach($this->routes() as $route)$sitemap.='<url><loc>'.e(Config::site().'/'.$route).'</loc></url>';$sitemap.='</urlset>';atomic($directory.'/sitemap.xml',$sitemap);atomic($directory.'/.nojekyll','');atomic($directory.'/robots.txt',"User-agent: *\nAllow: /\nSitemap: ".Config::site()."/sitemap.xml\n");$files=array_merge($files,['sitemap.xml','.nojekyll','robots.txt']);
  $release=['version'=>VERSION,'content_digest'=>hash('sha256',json($this->data))];atomic($directory.'/release.json',json($release));$files[]='release.json';$hashes=[];foreach($files as $file)$hashes[$file]=hash_file('sha256',$directory.'/'.$file);ksort($hashes);return ['files'=>$hashes,'digest'=>hash('sha256',json($hashes)),'bytes'=>array_sum(array_map(fn($f)=>filesize($directory.'/'.$f),$files)),'content_digest'=>$release['content_digest']];
 }
}
