<?php
declare(strict_types=1);
namespace Ted2;
final class Publisher {
 const REPOSITORY='MPHILL-LAB-TRACKER/MPHILL-research-2026';const BRANCH='gh-pages';
 public string $directory;
 public function __construct(public Store $store,public string $root=ROOT,public bool $allowLocal=false){$this->root=realpath($root)?:$root;$this->directory=dirname($store->db->path).'/publishing-v6';dirPrivate($this->directory);}
 public function git(array $args,string $input='',array $env=[],int $timeout=90):string{$r=Process::run(array_merge(['git','-C',$this->root,'-c','core.hooksPath=/dev/null'],$args),$input,$timeout,$this->root,$env);ensure($r['code']===0,409,'Git operation failed. Check your terminal Git credentials, identity, repository permission and branch protection. No force push was used.');return trim($r['out']);}
 public function config():array{$top=$this->git(['rev-parse','--show-toplevel']);ensure(realpath($top)===$this->root,409,'Start in the actual MPHILL-research-2026 clone, not its parent.');$urls=explode("\n",$this->git(['remote','get-url','--push','--all','origin']));ensure(count($urls)===1,409,'Exactly one origin push destination is required.');$url=$urls[0];ensure(preg_match('#^(?:https://github\.com/|git@github\.com:|ssh://git@github\.com/)'.preg_quote(self::REPOSITORY,'#').'(?:\.git)?$#iD',$url)===1||($this->allowLocal&&str_starts_with($url,'/')),409,'Origin must be the expected GitHub repository, without embedded credentials.');return ['repository'=>self::REPOSITORY,'branch'=>self::BRANCH,'remote'=>$url,'website'=>Config::site().'/'];}
 private function locked(callable $f):mixed{$fp=fopen($this->directory.'/lock','c');ensure(flock($fp,LOCK_EX|LOCK_NB),409,'A preview or publication is already running.');try{return $f();}finally{flock($fp,LOCK_UN);fclose($fp);}}
 public function gh(array $args):array{$r=Process::run(array_merge(['gh','api'], $args),seconds:30,cwd:$this->root);ensure($r['code']===0,503,'GitHub Pages status is unavailable. Sign in with gh auth login; permissions to read Pages may be needed.');return $r['out']!==''?decode($r['out']):[];}
 public function status(?string $commit=null):array{
  $config=$this->config();$out=$config+['configuration'=>'unknown','deployment'=>'unverified','message'=>'Git push and GitHub Pages deployment are separate steps.'];
  if($this->allowLocal)return $out+['test_remote'=>true];
  try{$pages=$this->gh(['repos/'.self::REPOSITORY.'/pages']);$out['source']=$pages['source']??[];$out['build_type']=$pages['build_type']??'';$out['configuration']=($out['source']['branch']??'')===self::BRANCH&&($out['source']['path']??'')==='/'&&$out['build_type']==='legacy'?'ready':'mismatch';$out['message']=$out['configuration']==='ready'?'Pages is configured for gh-pages / (root).':'Pages is not configured for gh-pages / (root). Use Configure Pages before publishing.';
   if($commit){ensure(preg_match('/^[a-f0-9]{40,64}$/D',$commit)===1,422,'Invalid commit.');$runs=$this->gh(['repos/'.self::REPOSITORY.'/actions/runs?head_sha='.$commit.'&per_page=10']);$found=null;foreach($runs['workflow_runs']??[] as $run)if(($run['name']??'')==='pages build and deployment'){$found=$run;break;}if($found){$out['deployment']=$found['conclusion']??$found['status'];$out['run_url']=$found['html_url'];}else $out['deployment']='not-started';}
  }catch(Problem $e){$out['status_warning']=$e->getMessage();}return $out;
 }
 public function configure(array $u):array{Auth::owner($u);$this->config();$this->gh(['--method','PUT','repos/'.self::REPOSITORY.'/pages','-f','build_type=legacy','-f','source[branch]=gh-pages','-f','source[path]=/']);$this->store->audit($u['username'],'configure-pages','website','github');return $this->status();}
 public function prepare(array $u):array{Auth::admin($u);$this->config();return $this->locked(function()use($u){$id=id();$dir=$this->directory.'/'.$id;$manifest=(new PublicSite($this->store,true))->build($dir.'/site');$manifest+=['id'=>$id,'user_id'=>$u['id'],'created'=>time(),'published'=>false];atomic($dir.'/manifest.json',json($manifest));return ['id'=>$id,'files'=>count($manifest['files']),'bytes'=>$manifest['bytes'],'digest'=>$manifest['digest'],'preview_url'=>'/api/publish/preview/'.$id.'/index.html','branch'=>self::BRANCH];});}
 public function manifest(array $u,string $id):array{ensure(preg_match('/^[a-f0-9]{32}$/D',$id)===1,404,'Preview not found.');$path=$this->directory.'/'.$id.'/manifest.json';ensure(is_file($path),404,'Preview not found.');$m=decode(file_get_contents($path));ensure($m['user_id']===$u['id'],403,'Prepare your own preview.');ensure(time()-$m['created']<1800,409,'Preview expired. Prepare a fresh preview.');return $m;}
 public function push(array $u,string $id):array{Auth::admin($u);$config=$this->config();return $this->locked(function()use($u,$id,$config){
  $m=$this->manifest($u,$id);ensure(empty($m['published']),409,'This preview was already pushed.');
  $check=$this->directory.'/check-'.id();try{$fresh=(new PublicSite($this->store,true))->build($check);ensure(hash_equals($m['digest'],$fresh['digest']),409,'Public content changed since preview. Prepare another preview.');}finally{self::removeTree($check);}
  $site=$this->directory.'/'.$id.'/site';foreach($m['files'] as $name=>$hash)ensure(!is_link($site.'/'.$name)&&is_file($site.'/'.$name)&&hash_equals($hash,hash_file('sha256',$site.'/'.$name)),409,'Preview integrity changed. Prepare another preview.');
  $tip=$this->git(['ls-remote','--heads',$config['remote'],'refs/heads/'.self::BRANCH]);$parent=$tip?preg_split('/\s+/',$tip)[0]:'';if($parent){ensure(preg_match('/^[a-f0-9]{40,64}$/D',$parent)===1,409,'Invalid remote response.');$this->git(['fetch','--no-tags','--no-write-fetch-head',$config['remote'],$parent]);}
  $gitdir=$this->git(['rev-parse','--absolute-git-dir']);$index=$this->directory.'/index-'.id();$env=['GIT_DIR'=>$gitdir,'GIT_WORK_TREE'=>$site,'GIT_INDEX_FILE'=>$index];
  try{$this->git(['read-tree','--empty'],env:$env);$lines='';foreach($m['files'] as $name=>$hash){$blob=$this->git(['hash-object','-w','--stdin'],file_get_contents($site.'/'.$name),$env);$lines.='100644 '.$blob."\t".$name."\0";}$this->git(['update-index','-z','--index-info'],$lines,$env);$tree=$this->git(['write-tree'],env:$env);$args=['commit-tree',$tree];if($parent)$args=array_merge($args,['-p',$parent]);$args=array_merge($args,['-m','Publish TED2 V6 approved website · '.substr($id,0,8)]);$commit=$this->git($args,env:$env);$this->git(['push','--porcelain',$config['remote'],$commit.':refs/heads/'.self::BRANCH],timeout:180);}finally{if(is_file($index))unlink($index);}
  $m['published']=true;$m['commit']=$commit;atomic($this->directory.'/'.$id.'/manifest.json',json($m));$this->store->audit($u['username'],'publish-github','website',$id,null,['commit'=>$commit,'branch'=>self::BRANCH]);$status=$this->status($commit);
  return ['ok'=>true,'commit'=>$commit,'branch'=>self::BRANCH,'website'=>$config['website'],'message'=>'Commit pushed. Deployment is NOT confirmed until GitHub Pages reports success.','pages'=>$status];
 });}
 public static function removeTree(string $p):void{if(!is_dir($p))return;foreach(new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($p,\FilesystemIterator::SKIP_DOTS),\RecursiveIteratorIterator::CHILD_FIRST) as $f){if($f->isDir()&&!$f->isLink())rmdir($f->getPathname());else unlink($f->getPathname());}rmdir($p);}
}
